name: ExtraData Scanner

on:
  workflow_dispatch:
    inputs:
      rpc_url:
        description: "RPC URL"
        required: true
        type: string
      start_block:
        description: "Start block number"
        required: false
        type: string
        default: "0"
      end_block:
        description: "End block number"
        required: false
        type: string
        default: ""
      workers:
        description: "Number of workers for parallel processing"
        required: false
        type: string
        default: "10"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run scanner
        env:
          RPC_URL: ${{ inputs.rpc_url }}
          START_BLOCK: ${{ inputs.start_block }}
          END_BLOCK: ${{ inputs.end_block }}
        run: |
          END_BLOCK_ARG=""
          if [ ! -z "$END_BLOCK" ]; then
            END_BLOCK_ARG="--end=$END_BLOCK"
          fi

          WORKERS_ARG=""
          if [ ! -z "$WORKERS" ]; then
            WORKERS_ARG="--workers=$WORKERS"
          fi

          go run cmd/extradata-scanner/main.go \
            --rpc=$RPC_URL \
            --start=$START_BLOCK \
            $END_BLOCK_ARG \
            $WORKERS_ARG
